apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0    # MySQL version 8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"   # Change this to a secure password
            - name: MYSQL_DATABASE
              value: "mydatabase"     # Name of the default database
            - name: MYSQL_USER
              value: "myuser"         # Username for the database
            - name: MYSQL_PASSWORD
              value: "mypassword"     # Password for the user
          ports:
            - containerPort: 3306
              name: mysql
