name: MySQL and pytest

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Remove existing MySQL container
        run: |
          docker rm -f mysql-test || true

               
      - name: Stop and remove existing Flask container (if exists)
        run: |
          docker rm -f flask-container || true

      - uses: actions/checkout@v3


      - name: Start MySQL
        run: |
          docker run -d \
            --name mysql-test \
            --network host \
            -e MYSQL_ROOT_PASSWORD=123456 \
            -e MYSQL_DATABASE=testdb \
            -p 3306:3306 \
            mysql:8.0
        
      - name: Wait for MySQL to be ready
        run: |
          # Wait for MySQL to be ready
          for i in {1..30}; do
            if docker exec mysql-test mysqladmin ping -h localhost -u root -p123456 --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 1
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker builder prune -f
          docker build --no-cache -t flask-app .

      - name: Build Docker image
        run: |
          docker build -t flask-app .
      
      - name: Start Flask app in the background
        run: |
          docker run -d --network host -p 5000:5000 --name flask-container flask-app

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: 123456
        run: |
          pytest tests/test_app.py


