name: Docker Build and Push

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Docker Hub
      - name: Authenticate with Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          if [ $? -eq 0 ]; then
            echo "Successfully authenticated with Docker Hub"
          else
            echo "Authentication failed"
            exit 1
          fi          

      # Step 3: Set a unique image tag using the commit hash
      - name: Get unique image tag
        id: vars
        run: |
          UNIQUE_TAG=$(git rev-parse --short HEAD)
          echo "UNIQUE_TAG=${UNIQUE_TAG}" >> $GITHUB_ENV          

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.UNIQUE_TAG }} .          

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.UNIQUE_TAG }}          

      # Step 6: Logout from Docker Hub (optional cleanup)
      - name: Logout from Docker Hub
        run: |
          docker logout      
